### ISSUE TITLE
cutscene editor: rename fade-in and fade-out to dim/undim

### ISSUE THREAD

**Issue by seiyria** [MagicConnect/unity-client#8]
this would make more sense with how they work.

alternatively, we could have a new "play_effect fadein center" sort of syntax for generic effects.

**Comment by civilityreigns** [comment]
Added new dimming/undimming commands with 2ffc05b1e6ef1a5f7af5166b6baf4a820f93dc41. The Yarn Spinner commands are:
- dim_character (float timeToAnimate = 0.2f, bool waitForAnimation = false)
- undim_character (float timeToAnimate = 0.2f, bool waitForAnimation = false)
- dim_characters (GameObject character1 = null, ... GameObject character6 = null, float timeToAnimate = 0.2f, bool waitForAnimation = false)
- undim_characters (GameObject character1 = null, ... GameObject character6 = null, float timeToAnimate = 0.2f, bool waitForAnimation = false)
- dim_two_characters (GameObject character1, GameObject character2, float timeToAnimate = 0.2f, bool waitForAnimation = false)
- dim_three_characters (GameObject character1, ... GameObject character3, float timeToAnimate = 0.2f, bool waitForAnimation = false)
- dim_four_characters (GameObject character1, ... GameObject character4, float timeToAnimate = 0.2f, bool waitForAnimation = false)
- dim_five_characters (GameObject character1, ... GameObject character5, float timeToAnimate = 0.2f, bool waitForAnimation = false)
- undim_two_characters (GameObject character1, GameObject character2, float timeToAnimate = 0.2f, bool waitForAnimation = false)
- undim_three_characters (GameObject character1, ... GameObject character3, float timeToAnimate = 0.2f, bool waitForAnimation = false)
- undim_four_characters (GameObject character1, ... GameObject character4, float timeToAnimate = 0.2f, bool waitForAnimation = false)
- undim_five_characters (GameObject character1, ... GameObject character5, float timeToAnimate = 0.2f, bool waitForAnimation = false)
- switch_dimmed_character (GameObject character1, GameObject character2, float timeToComplete = 0.2f, bool waitForAnimation = false, bool undimFirstCharacter = false, bool undimSecondCharacter = false)

Whenever I reach a good checkpoint on the cutscene features I'll write up a guide on the wiki on how to use all this. Essentially wherever there's a GameObject character, you just use the name of the character/npc. For timeToAnimate, that's how long in seconds it should take the animation to play. waitForAnimation determines whether the cutscene waits for the animation to complete before moving to the next step.

Yarn Spinner has some annoying limitations when it comes to overloaded methods and variable arguments, so I had to add a bunch of helper commands for dimming/undimming multiple characters (in case the writers don't feel like writing out multiple dim/undim commands). For example, saying '<<dim_characters Beryl-Vegha Lana-Elenore>>' works, but '<<dim_characters Beryl-Vegha Lana-Elenore 0.5 waitForAnimation>>' does not, and throws an exception because the 0.5 float value and waitForAnimation boolean value cannot be converted to GameObjects. '<<dim_two_characters Beryl-Vegha Lana-Elenore 0.5 waitForAnimation>>' is the alternative.

'switch_dimmed_character' is a simple command for alternating between which characters are dimmed, like in a conversation. It's potentially a faster way of writing out <<dim_character CharacterA>><<undim_character CharacterB>>. All it does is toggle whether the two characters are dimmed or not, so if both characters have the same dimmed state then the undimFirstCharacter/undimSecondCharacter flags should be used to force one of them to be undimmed, or you could just use a 'dim_character' command and 'switch_dimmed_character every time afterwards like a normal person.
